iCrawl/discord-vscode

package.json
src/extension.ts

There are times where I use vscode without having discord started, so this configuration option allows me to hide the error which shows when I have no client started:
(also shouldn't this be "No Discord Client detected!"?)

Add a configuration option to silence error messages

---

package.json
src/extension.ts

Was kind of bored, so I implemented a thing from #12.
Quick summary of changes:
- Added a `"discord.workspaceElapsedTime"` boolean setting that defaults to false (so the current extension functionality is preserved).
- `setActivity` now takes a `boolean` parameter for the `workspaceElapsedTime` setting that defaults to `false`. If true, the function sets `activity.startTimestamp` to the previous timestamp (if available), thus preserving the workspace's elapsed time. Otherwise, it generates a new timestamp as usual.
- Added an if-else block that passes either `setActivity(true)` or `setActivity()` as event handlers, depending on the `workspaceElapsedTime` setting.
- All changes are tslint-approved and certified.

Add workspace elapsed time feature

---

package.json
src/extension.ts

Messed up the expression to determine the start timestamp in the last PR, which was causing the extension to always display workspace elapsed time regardless of setting. It should be fixed with this PR.
The expression now goes like this:
```
If a previous timestamp exists, and the user wants workspace elapsed time,
set startTimestamp to previousTimestamp.
Else (no previous timestamp or the user wants file elapsed time),
generate a new timestamp for startTimestamp.
```

Fix boolean expression to determine start timestamp

---

src/extension.ts

Because well... In my opinion it looked bad.

misc: Capitalize Discord and RPC in an error message

---

README.md
src/extension.ts

- Added 
to display when the client is attempting to reconnect
- Removed reconnect timer, in favor of recursion (the timer would attempt to reconnect before the previous attempt would timeout)
- Re-connection message now respects `discord.silent`
- Created a branch so I would not screw up the commits

Reconnection bugfixes and improvements

---

package.json
src/extension.ts

This PR allows people to set custom things like `Editing a JS file` in the large image text, should they choose so.
Naming of the parameters can be changed if needed. But as they stand right now, I feel like they match what they do.
This closes #26

feature: Allow the language key to be added to the largeImage text

---

src/extension.ts

This PR fixes the desync issues that happen when you update the config, but not reload.
Before it would just ignore the new settings till you reloaded. Now, it gets updated before setting the activity.
Fixes #27

fix: Desync issues with config updates

---

src/extension.ts

This PR fixes `discord.disable`, as the config would not update when the command was ran, never knowing that you actually disabled the extension in the workspace.
Also did some aesthetic changes to the disable command

fix: Disable command not working well

---

package.json
src/extension.ts

Closes #31 
This PR allows people to have an empty state or description to be empty (it actually is a double 0-width space, it's the only way to do this).
So, if a user sets their `lowerDetailsEditing` to `{null}`, it will show an empty space. It's a limitation that we cannot overcome

feat: Allow people to set the state or description section to be empty

---

src/extension.ts

Not needed anyways, and buggy to say the least.
Closes #51

fix: Don't show a timer on idle

---

src/extension.ts

~This PR removed the `lastKnownFileName` to allow more "live" changes to a file (line number, file size, etc).~
This PR improves the `lastKnownFile` (previously `lastKnownFileName`), to where if you are in the same file, it just updates the necessary informations instead of the whole activity object.

[RFC] Change the activity setter if you are in the same file

---

package.json

As, its details.Debugging shouldn't it be, "Debugging {filename}" as opposed to "Editing {filename}" similar to how it is in discord.lowerDetailsDebugging

Fix to default settings

---

src/data/languages.json

DreamMaker is a language for the [BYOND game engine](https://secure.byond.com/).
Suggested image:

Adds DreamMaker support

---

src/data/languages.json

.sp files are used for [SourcePawn](https://wiki.alliedmods.net/Introduction_to_SourcePawn_1.7) development which, as the name suggests, is part of the Pawn language

add support for .sp files (SourcePawn)

---

src/data/languages.json

Add support for reasonml files in rich presence, with logo as below

Add reasonml support

---

package.json
src/client/RPCClient.ts
src/constants.ts
src/extension.ts
src/structures/Activity.ts

Since the rewrite, there were a couple of bugs that made the extension just... not work.
A list of things changed:
- Recreate the RPC Client instance on every login call
- We cannot re-use the client
- Update the config when you use the enable, disable, or reconnect command, as well as every 15 seconds before setting the activity
- Otherwise, disable never disables, and activity strings never update.
- Moved the status bar item to have a reference in the client
- Hide it instead of removing it
- Moved the ready logic inside login, since it needs to be set on every client anyways
- tslint a few things
- This is with my rule-set which I didn't commit as it's outside the scope of this PR. I can commit it in another PR, if wanted.

fix: Loads of bugs n quirks

---

package.json

As mentioned in #117, I believe this is enough to add a reconnect command to the `(Ctrl | Cmd) + Shift + P` menu.

Add `discord.reconnect` as a command

---

src/data/languages.json

I'm not sure how the icon works. Is there another step I need to perform elsewhere?

Add PureScript to known languages

---

src/data/languages.json

More info: https://webpack.js.org/configuration/configuration-languages/
I only add most common file extensions, and some of them are extensions that I personally use.
closes: #634

feat: update webpack config extensions

---

src/data/languages.json

The new Phoenix live views in elixir are named `.html.leex` instead of `.html.eex` so this should help display those files as well

feat: add live embedded elixir templates to existing eex icon

---

src/data/languages.json

Added .ss and .scm to a list of known extensions and marked them as being within lisp.

feat: .ss and .scm to known extensions

---

src/data/languages.json

The image should be the same as the existing `pawn` if possible. SourcePawn is a fork of the original language but doesn't have its own logo.
Closes #843

feat: change .sp extension to SourcePawn

---

src/activity.ts

Git repositories with no remotes just caused the set activity function to error out, this fixes that.
Fixes #1009

fix: presence erroring on update if no remote url
